# Generated by Django 4.2.4 on 2023-08-30 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='photographycategory',
            new_name='categoryDB',
        ),
    ]
