# Generated by Django 4.2.4 on 2023-09-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_clientdb_coverimages_imagesdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingPackageDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('includes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
