# Generated by Django 4.2.4 on 2023-09-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_bookindb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookindb',
            name='Mobile',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
